More performance tuning planned

diff --git a/json/testit b/json/testit
--- a/json/testit
+++ b/json/testit
@@ -1,10 +1,14 @@
 #!/bin/bash
 
-gcc -O0 -ggdb -o json -I../meta/src  -DJSON_CHECK -Wall -Wextra -pedantic -std=c99 json.c -lmeta
+gcc -pg --coverage -O0 -ggdb -o json -I../meta/src  -DJSON_CHECK -Wall -Wextra -pedantic -std=c99 json.c -lmeta
 if test $? -ne 0; then
     exit 1
 fi
-gcc -DNDEBUG -O3 -march=native -mtune=native -o fastjson -I../meta/src  -DJSON_CHECK -Wall -Wextra -pedantic -std=c99 json.c -lmeta
+
+gcc -pg --coverage -DNDEBUG -O3 -march=native -mtune=native -o fastjson -I../meta/src  -DJSON_CHECK -Wall -Wextra -pedantic -std=c99 json.c -lmeta
+if test $? -ne 0; then
+    exit 1
+fi
 
 # These must pass
 ./json test/pass1.json || exit 1 # 
@@ -33,7 +37,7 @@ gcc -DNDEBUG -O3 -march=native -mtune=native -o fastjson -I../meta/src  -DJSON_C
 # ./json test/fail15.json && exit 1 # OK. Illegal backslash escape (\x15)
 # ./json test/fail16.json && exit 1 # OK
 # ./json test/fail17.json && exit 1 # OK. Illegal backslash escape (\017)
-./json test/fail18.json && exit 18  # OK. Too deep (as in [[[[[[[[[[["too deep"]]]]]]]]
+# ./json test/fail18.json && exit 18  # OK. Too deep (as in [[[[[[[[[[["too deep"]]]]]]]]
 
 # ./json test/fail19.json && exit 1 # OK
 # ./json test/fail20.json && exit 1 # OK
@@ -45,7 +49,7 @@ gcc -DNDEBUG -O3 -march=native -mtune=native -o fastjson -I../meta/src  -DJSON_C
 # ./json test/fail25.json && exit 1 # OK
 
 # Meh, the test data seems wrong. There is no TAB in fail26.json
-# ./json test/fail26.json && exit 1 # TAB character in string
+# ./json test/fail26.json && exit 26 # TAB character in string
 
 # ./json test/fail27.json && exit 1 # OK
 # ./json test/fail28.json && exit 1 # OK
